### ISSUE TITLE
Laravel Lumen 5.7 Error

### ISSUE THREAD

**Issue by MrWildanMD** [hedii/laravel-gelf-logger#48]
Got exception like this,,,installed version: "hedii/laravel-gelf-logger": "^3.1",
```
[2023-11-30 13:49:10] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Class 'Hedii\\LaravelGelfLogger\\Processors\\RenameIdFieldProcessor' not found at /var/www/vendor/hedii/laravel-gelf-logger/src/GelfLoggerFactory.php:72)
[stacktrace]
#0 /var/www/vendor/illuminate/log/LogManager.php(205): Hedii\\LaravelGelfLogger\\GelfLoggerFactory->__invoke(Array)
#1 /var/www/vendor/illuminate/log/LogManager.php(178): Illuminate\\Log\\LogManager->createCustomDriver(Array)
#2 /var/www/vendor/illuminate/log/LogManager.php(102): Illuminate\\Log\\LogManager->resolve('gelf')
#3 /var/www/vendor/illuminate/log/LogManager.php(90): Illuminate\\Log\\LogManager->get('gelf')
#4 /var/www/vendor/illuminate/log/LogManager.php(79): Illuminate\\Log\\LogManager->driver('gelf')
#5 /var/www/vendor/illuminate/support/Facades/Facade.php(237): Illuminate\\Log\\LogManager->channel('gelf')
#6 /var/www/app/Http/Controllers/EjbcaController.php(1656): Illuminate\\Support\\Facades\\Facade::__callStatic('channel', Array)
#7 [internal function]: App\\Http\\Controllers\\EjbcaController->ping(Object(Laravel\\Lumen\\Http\\Request))
#8 /var/www/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /var/www/vendor/illuminate/container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/vendor/illuminate/container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#11 /var/www/vendor/illuminate/container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#12 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(378): Illuminate\\Container\\Container->call(Array, Array)
#13 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(344): Laravel\\Lumen\\Application->callControllerCallable(Array, Array)
#14 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(318): Laravel\\Lumen\\Application->callLumenController(Object(App\\Http\\Controllers\\EjbcaController), 'ping', Array)
#15 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(280): Laravel\\Lumen\\Application->callControllerAction(Array)
#16 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(265): Laravel\\Lumen\\Application->callActionOnArrayBasedRoute(Array)
#17 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(165): Laravel\\Lumen\\Application->handleFoundRoute(Array)
#18 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(418): Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))
#19 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(171): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))
#20 /var/www/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)
#21 /var/www/public/index.php(29): Laravel\\Lumen\\Application->run()
#22 {main}
"} 
```

when installing the latest version got error:
```
root@c5e200d9f50e:/var/www# composer require hedii/laravel-gelf-logger
Using version ^6.2 for hedii/laravel-gelf-logger
./composer.json has been updated
Running composer update hedii/laravel-gelf-logger
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires hedii/laravel-gelf-logger ^6.2 -> satisfiable by hedii/laravel-gelf-logger[6.2.0].
    - hedii/laravel-gelf-logger 6.2.0 requires illuminate/log ^8.12 -> found illuminate/log[v8.12.0, ..., 8.x-dev] but the package is fixed to v5.7.28 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require hedii/laravel-gelf-logger:*" to figure out if any version is installable, or "composer require hedii/laravel-gelf-logger:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
How to resolve this? thanks

**Comment by hedii** [comment]
Hi,

"hedii/laravel-gelf-logger": "^3.1" does not contain RenameIdFieldProcessor, so don't add it to your configuration file.

Also, I have never used lumen, so I don't know if this package is compatible with lumen : it is designed for laravel
